//! `docs/keybindings.md`, generated from the action registry and the built-in tables
//! so it never drifts from the code (sverb `keymap/dump.rs`, D13). Regenerate with
//! `COURIER_FTP_BLESS=1 cargo test -p courier-ftp keybindings_doc`; T77 publishes it.

use std::fmt::Write as _;

use strum::IntoEnumIterator;

use super::{
    chord::KeyChord,
    dump::grouped,
    map::{Keymap, RawKeymap},
};
use crate::app::Mode;

/// Grammar, timeout, caveats and the `"none"` rule.
const DOCS_INTRO: &str = include_str!("docs_intro.md");

fn md_keys(keys: &[String]) -> String {
    keys.iter()
        .map(|k| format!("`{}`", k.replace('|', "\\|")))
        .collect::<Vec<_>>()
        .join(", ")
}

fn mode_intro(mode: Mode) -> &'static str {
    match mode {
        Mode::Normal => {
            "Global: consulted in every non-modal mode after the focused region's table."
        }
        Mode::FileList => "A file list has the focus.",
        Mode::Tree => "A directory tree has the focus.",
        Mode::Log => "The message log has the focus.",
        Mode::Queue => "The queue has the focus.",
        Mode::SiteManager => {
            "The Site Manager's tree has the focus (the editor on the right uses `Dialog`). \
             The Site Manager is modal, so only this table is consulted."
        }
        Mode::Filter => "Typing a quick filter; printable keys and `backspace` go to the field.",
        Mode::Input => {
            "A single-line field outside dialogs (quickconnect, the `:` line, log search)."
        }
        Mode::Dialog => "A dialog or overlay is open; only this table is consulted.",
    }
}

/// `docs/keybindings.md` for the built-in tables `defaults` (generated by the
/// `keybindings_doc_is_current` test; T77 publishes it).
pub(crate) fn markdown(defaults: &RawKeymap) -> String {
    let (keymap, _) = Keymap::build(defaults, &RawKeymap::new());
    let mut out = String::new();
    out.push_str(
        "<!-- Generated from crates/courier-ftp/src/action.rs (registry) and \
         crates/courier-ftp/config/config.json (tables). Do not edit:\n     \
         run `COURIER_FTP_BLESS=1 cargo test -p courier-ftp keybindings_doc` to regenerate. -->\n\n",
    );
    // A checkout with CRLF line endings must not change the output.
    out.push_str(&DOCS_INTRO.replace("\r\n", "\n"));
    for mode in Mode::iter() {
        let rows = keymap.table_rows(mode);
        let _ = writeln!(out, "\n## `{mode:?}`\n\n{}", mode_intro(mode));
        if rows.is_empty() {
            out.push_str("\nNo bindings.\n");
            continue;
        }
        for (group, entries) in grouped(&rows) {
            let _ = writeln!(out, "\n### {}\n", group.title());
            out.push_str("| Keys | Action | Description | Owner |\n|---|---|---|---|\n");
            for (action, keys) in entries {
                let (desc, owner) = action.meta().map_or(("", ""), |m| (m.description, m.owner));
                let _ = writeln!(
                    out,
                    "| {} | `{action}` | {desc} | {owner} |",
                    md_keys(&keys)
                );
            }
        }
        if mode == Mode::Normal {
            let cx = KeyChord::ctrl('x');
            let cont = keymap.continuations(&[Mode::Normal], &[cx]);
            let _ = writeln!(
                out,
                "\n### The `ctrl-x` prefix\n\n\
                 Press `ctrl-x`, then one of these keys ({} in all; the popup lists them).\n\n\
                 | Key | Action | Description |\n|---|---|---|",
                cont.len()
            );
            for (k, a) in cont {
                let desc = a.meta().map_or("", |m| m.description);
                let _ = writeln!(out, "| {} | `{a}` | {desc} |", md_keys(&[k.to_string()]));
            }
        }
    }
    out
}
